apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "apis.oda.tmforum.org"
spec:
  group: "oda.tmforum.org"
  version: "v1alpha1"
  scope: "Namespaced"
  names:
    plural: "apis"
    singular: "api"
    kind: "api"
  additionalPrinterColumns:
  - name: API_endpoint
    type: string
    description: API endpoint Url
    JSONPath: .status.ingress.url    