apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: compcrdwebhook.canvas.svc
spec:
  groups:
  - systemauthenticated
  request: W3JlcV0NCnJlcV9leHRlbnNpb25zID0gdjNfcmVxDQpkaXN0aW5ndWlzaGVkX25hbWUgPSByZXFfZGlzdGluZ3Vpc2hlZF9uYW1lDQpbcmVxX2Rpc3Rpbmd1aXNoZWRfbmFtZV0NClsgdjNfcmVxIF0NCmJhc2ljQ29uc3RyYWludHMgPSBDQTpGQUxTRQ0Ka2V5VXNhZ2UgPSBub25SZXB1ZGlhdGlvbiwgZGlnaXRhbFNpZ25hdHVyZSwga2V5RW5jaXBoZXJtZW50DQpleHRlbmRlZEtleVVzYWdlID0gc2VydmVyQXV0aA0Kc3ViamVjdEFsdE5hbWUgPSBAYWx0X25hbWVzDQpbYWx0X25hbWVzXQ0KRE5TLjEgPSBjb21wY3Jkd2ViaG9vaw0KRE5TLjIgPSBjb21wY3Jkd2ViaG9vay5jYW52YXMNCkROUy4zID0gY29tcGNyZHdlYmhvb2suY2FudmFzLnN2Yw0KRE5TLjQgPSBjb21wY3Jkd2ViaG9vay5jYW52YXMuc3ZjLmNsdXN0ZXIubG9jYWw=
  usages:
  - digital signature
  - key encipherment
  - server auth