---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: odacomponent-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: odacomponent-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [oda.tmforum.org]
    resources: [components]
    verbs: [list, watch, patch, get]
  - apiGroups: [oda.tmforum.org]
    resources: [apis]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: [wso2.com]
    resources: [apis]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods", "configmaps"]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: [list, watch, patch, get, create, update, delete]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: odacomponent-role-namespaced
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [oda.tmforum.org]
    resources: [components]
    verbs: [list, watch, patch, get]
  - apiGroups: [oda.tmforum.org]
    resources: [apis]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: [wso2.com]
    resources: [apis]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "pods", "configmaps"]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: [list, watch, patch, get, create, update, delete]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: [list, watch, patch, get, create, update, delete]

  # Application: other resources it produces and manipulates.
  # Here, we create Jobs+PVCs+Pods, but we do not patch/update/delete them ever.
  - apiGroups: [batch, extensions]
    resources: [jobs]
    verbs: [create]
  - apiGroups: [""]
    resources: [pods, persistentvolumeclaims]
    verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odacomponent-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odacomponent-role-cluster
subjects:
  - kind: ServiceAccount
    name: odacomponent-account
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: odacomponent-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odacomponent-role-namespaced
subjects:
  - kind: ServiceAccount
    name: odacomponent-account